### ISSUE TITLE
where is  API   and  jar

### ISSUE THREAD

**Issue by a820366174** [x10-lang/xasdi#4]
I'm not  find  (XASDI API javadoc) and   (XASDI runtime jar file)  jar.would you tell me  where is?

**Comment by hmizuta** [comment]
By building the source codes, API javadoc and runtime jar file are generated. Please type "./build.sh" at src directory.

**Comment by a820366174** [comment]
I  type  “./build.sh” . but as result ,only runtime jar file are  generated,but API  javadoc is not generated,so  why?

**Comment by hmizuta** [comment]
After your first question, I modified the script to generate API javadoc. If you clone the repository before my answer, please pull the latest version.
You can also generate the API javadoc by typing "ant javadoc" at src/bridge directory.
