### ISSUE TITLE
something   is   wrong   with   “./run-Sample.sh"

### ISSUE THREAD

**Issue by a820366174** [x10-lang/xasdi#5]
how  can  I  solve  the  problem, I  Set up  build environment,but when  I   excute  "./run-Sample.sh"    ,it  always  has problem.
Removed old log and csv files.
Error: Cannot load main class for com.ibm.xasdi.runtime.XASDIRuntime with classpath /home/xu/xasdi-master/MySample/../jar/xasdi.jar:/home/xu/xasdi-master/MySample/mysample.jar:.:/home/xu/software-xasdi/stdlib/x10.jar:/home/xu/software-xasdi/lib/commons-math3-3.5.jar:/home/xu/software-xasdi/lib/commons-logging-1.2.jar:/home/xu/software-xasdi/lib/hazelcast-3.3.1.jar:/home/xu/software-xasdi/lib/snappy-java.jar
/usr/bin/java -ea -Djava.library.path=/home/xu/software-xasdi/lib -Djava.class.path=/home/xu/xasdi-master/MySample/../jar/xasdi.jar:/home/xu/xasdi-master/MySample/mysample.jar:.:/home/xu/software-xasdi/stdlib/x10.jar:/home/xu/software-xasdi/lib/commons-math3-3.5.jar:/home/xu/software-xasdi/lib/commons-logging-1.2.jar:/home/xu/software-xasdi/lib/hazelcast-3.3.1.jar:/home/xu/software-xasdi/lib/snappy-java.jar -Djava.util.logging.config.file=/home/xu/software-xasdi/lib/logging.properties -Xmx7000m -Xms1024m -Xss256m -Dxasdi.location.bootxml=/home/xu/xasdi-master/MySample/Sample/boot.xml -Dadaptive=false -DlogVhcl=true com.ibm.xasdi.runtime.XASDIRuntime$$Main
/home/xu/software-xasdi/bin/x10: 行 364: /home/xu/software-xasdi/bin/X10Launcher: 无法执行二进制文件
/home/xu/software-xasdi/bin/x10: 行 364: /home/xu/software-xasdi/bin/X10Launcher: success
finished

thanks

**Comment by hmizuta** [comment]
It looks that x10 cannot find XASDIRuntime class at /home/xu/xasdi-master/MySample/../jar/xasdi.jar
Can you check whether XASDIRuntime exist in /home/xu/xasdi-master/xasdi.jar ?
What is the output by the following command?

$ jar tf  /home/xu/xasdi-master/xasdi.jar | grep "XASDIRuntime"

Best regards,
